### ISSUE TITLE
git clone --recursive failure

### ISSUE THREAD

**Issue by est77** [superboubek/bcd#3]
error: Server does not allow request for unadvertised object ad8252c639801e53bdaac21d9ceddf1f6d894f26
Fetched in submodule path 'ext/nanogui', but it did not contain ad8252c639801e53bdaac21d9ceddf1f6d894f26. Direct fetching of that commit failed.

Following the github link to the nanogui commit shows a 404 error page.

https://github.com/wjakob/nanogui/tree/ad8252c639801e53bdaac21d9ceddf1f6d894f26

**Comment by superboubek** [comment]
This was fixed in a recent commit. Thanks for pointing our the issue.
